# Generated by Django 5.2.17 on 2026-08-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_connectee', '0003_studyroomreservation_delete_roomreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
    ]
